### Recuperar todos los usuarios
GET http://localhost:1234/costumes

### Recuperar un usuario por id
GET http://localhost:1234/costumes/247f78f1-866d-4ec4-b3e0-78c2ee1a0eea

### Recuperar todos los usuarios por un filtro
GET http://localhost:1234/costumes?category=Halloween

### Crear un usuario con POST
POST http://localhost:1234/costumes
Content-Type: application/json

{
    "name": "Doctor",
    "price": 8500,
    "category": "Profesiones",
    "details": "asdasd"
}

### Borrar un usuario
DELETE http://localhost:1234/costumes/0da923d6-d1bb-4a9c-b27a-69cc63ff8425

### Actualizar un usuario
PATCH http://localhost:1234/costumes/4be27f66-e350-4ce4-9b6b-97b54970d29c
Content-Type: application/json

{
    "id": "4be27f66-e350-4ce4-9b6b-97b54970d29c",
    "category": "Halloween",
    "details": "Asdasdasd",
    "dischargeDate": "",
    "name": "Jason 3",
    "precio": 10000
}
