### Recuperar todos los departamentos
GET http://localhost:1234/departaments

### Recuperar un categoria por id
GET http://localhost:1234/departaments/827a832b-6e4e-44d1-a839-abc63149238e

### Recuperar todos los departamentos por un filtro
GET http://localhost:1234/departaments?name=asd

### Crear un categoria con POST
POST http://localhost:1234/departaments
Content-Type: application/json

{
    "name": "Lujan"
}

### Borrar un categoria
DELETE http://localhost:1234/departaments/9468c92d-7dfe-43b0-831c-130420d87b03

### Actualizar un categoria
PATCH http://localhost:1234/departaments/a296abeb-c5a8-40b3-8dbf-02583dde3c9b
Content-Type: application/json

{
    "name": "Ciudad"
}
