### Recuperar todos los usuarios
GET http://localhost:1234/users

### Recuperar un usuario por id
GET http://localhost:1234/users/2

### Recuperar todos los usuarios por un filtro
GET http://localhost:1234/users?filtro=valor

### Crear un usuario con POST
POST http://localhost:1234/users
Content-Type: application/json

{
    "name": "Angel",
    "surname": "Vargas",
    "dni": 35123123,
    "phoneNumber": 2615123123,
    "email": "angelvargas@gmail.com",
    "direction": "Calle falsa 123",
    "departament": "Ciudad",
    "postalCode": 5539,
    "blacklist": false
}

### Borrar un usuario
DELETE http://localhost:1234/users/cbb524d9-2ef4-49ec-b355-a12f579fcd1d

### Actualizar un usuario
PATCH http://localhost:1234/users/dc569290-6003-4fd3-b499-749265f94c53
Content-Type: application/json

{
    "name": "Enzo"
}
